//Generated By moduleGenerator
#include "libSceGnmDriver.h"


int PS4_SYSV_ABI Ps4_sceGnmAddEqEvent(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmAddEqEvent");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmAreSubmitsAllowed(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmAreSubmitsAllowed");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmBeginWorkload(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmBeginWorkload");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmComputeWaitOnAddress(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmComputeWaitOnAddress");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmComputeWaitSemaphore(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmComputeWaitSemaphore");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmCreateWorkloadStream(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmCreateWorkloadStream");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDebuggerGetAddressWatch(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDebuggerGetAddressWatch");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDebuggerHaltWavefront(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDebuggerHaltWavefront");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDebuggerReadGds(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDebuggerReadGds");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDebuggerReadSqIndirectRegister(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDebuggerReadSqIndirectRegister");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDebuggerResumeWavefront(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDebuggerResumeWavefront");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDebuggerResumeWavefrontCreation(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDebuggerResumeWavefrontCreation");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDebuggerSetAddressWatch(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDebuggerSetAddressWatch");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDebuggerWriteGds(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDebuggerWriteGds");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDebuggerWriteSqIndirectRegister(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDebuggerWriteSqIndirectRegister");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDebugHardwareStatus(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDebugHardwareStatus");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDeleteEqEvent(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDeleteEqEvent");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDestroyWorkloadStream(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDestroyWorkloadStream");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDingDong(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDingDong");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDingDongForWorkload(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDingDongForWorkload");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDisableMipStatsReport(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDisableMipStatsReport");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDispatchDirect(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDispatchDirect");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDispatchIndirect(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDispatchIndirect");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDispatchIndirectOnMec(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDispatchIndirectOnMec");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDispatchInitDefaultHardwareState(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDispatchInitDefaultHardwareState");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawIndex(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawIndex");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawIndexAuto(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawIndexAuto");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawIndexIndirect(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawIndexIndirect");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawIndexIndirectCountMulti(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawIndexIndirectCountMulti");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawIndexIndirectMulti(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawIndexIndirectMulti");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawIndexMultiInstanced(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawIndexMultiInstanced");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawIndexOffset(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawIndexOffset");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawIndirect(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawIndirect");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawIndirectCountMulti(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawIndirectCountMulti");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawIndirectMulti(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawIndirectMulti");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawInitDefaultHardwareState(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawInitDefaultHardwareState");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawInitDefaultHardwareState175(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawInitDefaultHardwareState175");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawInitDefaultHardwareState200(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawInitDefaultHardwareState200");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawInitDefaultHardwareState350(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawInitDefaultHardwareState350");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawInitToDefaultContextState(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawInitToDefaultContextState");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawInitToDefaultContextState400(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawInitToDefaultContextState400");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawOpaqueAuto(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawOpaqueAuto");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDriverCaptureInProgress(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDriverCaptureInProgress");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDriverInternalRetrieveGnmInterface(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDriverInternalRetrieveGnmInterface");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForGpuDebugger(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForGpuDebugger");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForGpuException(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForGpuException");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForHDRScopes(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForHDRScopes");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForReplay(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForReplay");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForResourceRegistration(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForResourceRegistration");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForValidation(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForValidation");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDriverInternalVirtualQuery(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDriverInternalVirtualQuery");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDriverTraceInProgress(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDriverTraceInProgress");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDriverTriggerCapture(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDriverTriggerCapture");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmEndWorkload(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmEndWorkload");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmFindResourcesPublic(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmFindResourcesPublic");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmFlushGarlic(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmFlushGarlic");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetCoredumpAddress(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetCoredumpAddress");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetCoredumpMode(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetCoredumpMode");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetCoredumpProtectionFaultTimestamp(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetCoredumpProtectionFaultTimestamp");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetDbgGcHandle(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetDbgGcHandle");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetDebugTimestamp(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetDebugTimestamp");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetEqEventType(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetEqEventType");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetEqTimeStamp(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetEqTimeStamp");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetGpuBlockStatus(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetGpuBlockStatus");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetGpuCoreClockFrequency(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetGpuCoreClockFrequency");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetGpuInfoStatus(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetGpuInfoStatus");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetLastWaitedAddress(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetLastWaitedAddress");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetNumTcaUnits(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetNumTcaUnits");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetOffChipTessellationBufferSize(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetOffChipTessellationBufferSize");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetOwnerName(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetOwnerName");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetPhysicalCounterFromVirtualized(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetPhysicalCounterFromVirtualized");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetProtectionFaultTimeStamp(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetProtectionFaultTimeStamp");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetResourceBaseAddressAndSizeInBytes(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetResourceBaseAddressAndSizeInBytes");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetResourceName(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetResourceName");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetResourceShaderGuid(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetResourceShaderGuid");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetResourceType(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetResourceType");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetResourceUserData(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetResourceUserData");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetShaderProgramBaseAddress(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetShaderProgramBaseAddress");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetShaderStatus(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetShaderStatus");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetTheTessellationFactorRingBufferBaseAddress(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetTheTessellationFactorRingBufferBaseAddress");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGpuPaDebugEnter(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGpuPaDebugEnter");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGpuPaDebugLeave(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGpuPaDebugLeave");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmInsertDingDongMarker(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmInsertDingDongMarker");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmInsertPopMarker(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmInsertPopMarker");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmInsertPushColorMarker(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmInsertPushColorMarker");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmInsertPushMarker(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmInsertPushMarker");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmInsertSetColorMarker(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmInsertSetColorMarker");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmInsertSetMarker(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmInsertSetMarker");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmInsertThreadTraceMarker(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmInsertThreadTraceMarker");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmInsertWaitFlipDone(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmInsertWaitFlipDone");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmIsCoredumpValid(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmIsCoredumpValid");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmIsUserPaEnabled(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmIsUserPaEnabled");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmLogicalCuIndexToPhysicalCuIndex(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmLogicalCuIndexToPhysicalCuIndex");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmLogicalCuMaskToPhysicalCuMask(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmLogicalCuMaskToPhysicalCuMask");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmLogicalTcaUnitToPhysical(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmLogicalTcaUnitToPhysical");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmMapComputeQueue(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmMapComputeQueue");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmMapComputeQueueWithPriority(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmMapComputeQueueWithPriority");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmPaDisableFlipCallbacks(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmPaDisableFlipCallbacks");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmPaEnableFlipCallbacks(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmPaEnableFlipCallbacks");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmPaHeartbeat(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmPaHeartbeat");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmQueryResourceRegistrationUserMemoryRequirements(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmQueryResourceRegistrationUserMemoryRequirements");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmRaiseUserExceptionEvent(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmRaiseUserExceptionEvent");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmRegisterGdsResource(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmRegisterGdsResource");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmRegisterGnmLiveCallbackConfig(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmRegisterGnmLiveCallbackConfig");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmRegisterOwner(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmRegisterOwner");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmRegisterResource(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmRegisterResource");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmRequestFlipAndSubmitDone(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmRequestFlipAndSubmitDone");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmRequestFlipAndSubmitDoneForWorkload(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmRequestFlipAndSubmitDoneForWorkload");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmRequestMipStatsReportAndReset(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmRequestMipStatsReportAndReset");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmResetVgtControl(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmResetVgtControl");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSdmaClose(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSdmaClose");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSdmaConstFill(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSdmaConstFill");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSdmaCopyLinear(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSdmaCopyLinear");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSdmaCopyTiled(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSdmaCopyTiled");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSdmaCopyWindow(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSdmaCopyWindow");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSdmaFlush(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSdmaFlush");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSdmaGetMinCmdSize(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSdmaGetMinCmdSize");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSdmaOpen(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSdmaOpen");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetCsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetCsShader");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetCsShaderWithModifier(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetCsShaderWithModifier");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetEmbeddedPsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetEmbeddedPsShader");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetEmbeddedVsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetEmbeddedVsShader");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetEsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetEsShader");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetGsRingSizes(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetGsRingSizes");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetGsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetGsShader");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetHsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetHsShader");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetLsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetLsShader");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetPsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetPsShader");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetPsShader350(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetPsShader350");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetResourceRegistrationUserMemory(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetResourceRegistrationUserMemory");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetResourceUserData(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetResourceUserData");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetSpiEnableSqCounters(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetSpiEnableSqCounters");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetSpiEnableSqCountersForUnitInstance(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetSpiEnableSqCountersForUnitInstance");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetupMipStatsReport(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetupMipStatsReport");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetVgtControl(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetVgtControl");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetVsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetVsShader");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetWaveLimitMultiplier(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetWaveLimitMultiplier");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSetWaveLimitMultipliers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSetWaveLimitMultipliers");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSpmEndSpm(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSpmEndSpm");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSpmInit(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSpmInit");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSpmInit2(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSpmInit2");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSpmSetDelay(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSpmSetDelay");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSpmSetMuxRam(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSpmSetMuxRam");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSpmSetMuxRam2(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSpmSetMuxRam2");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSpmSetSelectCounter(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSpmSetSelectCounter");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSpmSetSpmSelects(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSpmSetSpmSelects");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSpmSetSpmSelects2(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSpmSetSpmSelects2");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSpmStartSpm(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSpmStartSpm");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttFini(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttFini");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttFinishTrace(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttFinishTrace");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttGetBcInfo(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttGetBcInfo");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttGetGpuClocks(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttGetGpuClocks");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttGetHiWater(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttGetHiWater");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttGetStatus(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttGetStatus");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttGetTraceCounter(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttGetTraceCounter");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttGetTraceWptr(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttGetTraceWptr");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttGetWrapCounts(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttGetWrapCounts");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttGetWrapCounts2(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttGetWrapCounts2");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttGetWritebackLabels(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttGetWritebackLabels");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttInit(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttInit");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttSelectMode(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttSelectMode");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttSelectTarget(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttSelectTarget");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttSelectTokens(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttSelectTokens");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttSetCuPerfMask(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttSetCuPerfMask");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttSetDceEventWrite(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttSetDceEventWrite");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttSetHiWater(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttSetHiWater");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttSetTraceBuffer2(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttSetTraceBuffer2");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttSetTraceBuffers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttSetTraceBuffers");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttSetUserData(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttSetUserData");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttSetUserdataTimer(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttSetUserdataTimer");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttStartTrace(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttStartTrace");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttStopTrace(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttStopTrace");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttSwitchTraceBuffer(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttSwitchTraceBuffer");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttSwitchTraceBuffer2(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttSwitchTraceBuffer2");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSqttWaitForEvent(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSqttWaitForEvent");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSubmitAndFlipCommandBuffers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSubmitAndFlipCommandBuffers");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSubmitAndFlipCommandBuffersForWorkload(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSubmitAndFlipCommandBuffersForWorkload");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSubmitCommandBuffers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSubmitCommandBuffers");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSubmitCommandBuffersForWorkload(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSubmitCommandBuffersForWorkload");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmSubmitDone(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmSubmitDone");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmUnmapComputeQueue(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmUnmapComputeQueue");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmUnregisterAllResourcesForOwner(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmUnregisterAllResourcesForOwner");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmUnregisterOwnerAndResources(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmUnregisterOwnerAndResources");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmUnregisterResource(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmUnregisterResource");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmUpdateGsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmUpdateGsShader");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmUpdateHsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmUpdateHsShader");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmUpdatePsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmUpdatePsShader");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmUpdatePsShader350(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmUpdatePsShader350");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmUpdateVsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmUpdateVsShader");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmValidateCommandBuffers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmValidateCommandBuffers");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmValidateDisableDiagnostics(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmValidateDisableDiagnostics");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmValidateDisableDiagnostics2(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmValidateDisableDiagnostics2");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmValidateDispatchCommandBuffers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmValidateDispatchCommandBuffers");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmValidateDrawCommandBuffers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmValidateDrawCommandBuffers");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmValidateGetDiagnosticInfo(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmValidateGetDiagnosticInfo");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmValidateGetDiagnostics(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmValidateGetDiagnostics");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmValidateGetVersion(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmValidateGetVersion");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmValidateOnSubmitEnabled(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmValidateOnSubmitEnabled");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmValidateResetState(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmValidateResetState");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmValidationRegisterMemoryCheckCallback(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmValidationRegisterMemoryCheckCallback");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceRazorCaptureCommandBuffersOnlyImmediate(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceRazorCaptureCommandBuffersOnlyImmediate");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceRazorCaptureCommandBuffersOnlySinceLastFlip(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceRazorCaptureCommandBuffersOnlySinceLastFlip");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceRazorCaptureImmediate(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceRazorCaptureImmediate");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceRazorCaptureSinceLastFlip(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceRazorCaptureSinceLastFlip");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceRazorIsLoaded(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceRazorIsLoaded");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncBj0GWi1jWcM(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncBj0GWi1jWcM");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncDKusr7JYQp0(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncDKusr7JYQp0");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncFQzzNvwumaM(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncFQzzNvwumaM");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncF8pof57lLUk(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncF8pof57lLUk");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncGHC4n3Wca0U(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncGHC4n3Wca0U");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncJvkCnvaKlV4(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncJvkCnvaKlV4");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncMB49u6sJLbA(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncMB49u6sJLbA");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncMLr+Fyrxf+8(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncMLr+Fyrxf+8");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncPmo+ggPZUxc(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncPmo+ggPZUxc");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncQP7vDGU0xDQ(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncQP7vDGU0xDQ");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncQWuQed5Mus4(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncQWuQed5Mus4");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncR3TYO7Tdv5o(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncR3TYO7Tdv5o");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncUGePHM7rmgA(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncUGePHM7rmgA");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncVKLsX6TGJBM(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncVKLsX6TGJBM");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncWpxSyDE4rms(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncWpxSyDE4rms");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncXSIZOjHqEUI(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncXSIZOjHqEUI");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_Funcclo23rtglI0(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_Funcclo23rtglI0");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncgCGlAvphubs(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncgCGlAvphubs");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncnQAv4PpA8OY(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncnQAv4PpA8OY");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncnSl-NqcCi3E(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncnSl-NqcCi3E");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncotfsenvPebM(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncotfsenvPebM");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncqhKjy4mQhUo(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncqhKjy4mQhUo");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncrcjdwAUCC8Y(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncrcjdwAUCC8Y");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncsKhoi2ectC0(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncsKhoi2ectC0");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FunctIkCC1FXpf8(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FunctIkCC1FXpf8");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_Funcut57TBmRQN0(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_Funcut57TBmRQN0");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_Func0VEbnc-7Pdk(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_Func0VEbnc-7Pdk");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_Func1TRGZJsC5Y4(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_Func1TRGZJsC5Y4");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_Func2Lbo4o4e8KM(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_Func2Lbo4o4e8KM");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_Func2T1zOhnddFQ(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_Func2T1zOhnddFQ");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_Func3plUQ7wqgxc(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_Func3plUQ7wqgxc");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_Func326VKBUMI-8(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_Func326VKBUMI-8");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_Func7LTGukH+M1A(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_Func7LTGukH+M1A");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDebugModuleReset(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDebugModuleReset");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDebugReset(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDebugReset");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncxMMot887QXE(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncxMMot887QXE");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawInitToDefaultContextStateInternalCommand(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawInitToDefaultContextStateInternalCommand");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmDrawInitToDefaultContextStateInternalSize(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmDrawInitToDefaultContextStateInternalSize");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmFindResources(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmFindResources");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmGetResourceRegistrationBuffers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmGetResourceRegistrationBuffers");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_sceGnmRegisterOwnerForSystem(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_sceGnmRegisterOwnerForSystem");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncHEOIaxbuVTA(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncHEOIaxbuVTA");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_FuncgQNwGezNDgE(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_FuncgQNwGezNDgE");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_Funcv7QcBXR48L8(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_Funcv7QcBXR48L8");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_Func5R1E24FRI4w(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_Func5R1E24FRI4w");
	return PS4_OK;
}

int PS4_SYSV_ABI Ps4_Func+RaJBCVJZVM(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Ps4_Func+RaJBCVJZVM");
	return PS4_OK;
}

void RegisterlibSceGnmDriver(Loader::SymbolsResolver * sym) {
 LIB_FUNCTION("b0xyllnVY-I, libSceGnmDriver , 1 , Ps4_sceGnmAddEqEvent ),
 LIB_FUNCTION("b08AgtPlHPg, libSceGnmDriver , 1 , Ps4_sceGnmAreSubmitsAllowed ),
 LIB_FUNCTION("ihxrbsoSKWc, libSceGnmDriver , 1 , Ps4_sceGnmBeginWorkload ),
 LIB_FUNCTION("ffrNQOshows, libSceGnmDriver , 1 , Ps4_sceGnmComputeWaitOnAddress ),
 LIB_FUNCTION("EJapNl2+pgU, libSceGnmDriver , 1 , Ps4_sceGnmComputeWaitSemaphore ),
 LIB_FUNCTION("5udAm+6boVg, libSceGnmDriver , 1 , Ps4_sceGnmCreateWorkloadStream ),
 LIB_FUNCTION("jwCEzr7uEP4, libSceGnmDriver , 1 , Ps4_sceGnmDebuggerGetAddressWatch ),
 LIB_FUNCTION("PNf0G7gvFHQ, libSceGnmDriver , 1 , Ps4_sceGnmDebuggerHaltWavefront ),
 LIB_FUNCTION("nO-tMnaxJiE, libSceGnmDriver , 1 , Ps4_sceGnmDebuggerReadGds ),
 LIB_FUNCTION("t0HIQWnvK9E, libSceGnmDriver , 1 , Ps4_sceGnmDebuggerReadSqIndirectRegister ),
 LIB_FUNCTION("HsLtF4jKe48, libSceGnmDriver , 1 , Ps4_sceGnmDebuggerResumeWavefront ),
 LIB_FUNCTION("JRKSSV0YzwA, libSceGnmDriver , 1 , Ps4_sceGnmDebuggerResumeWavefrontCreation ),
 LIB_FUNCTION("jpTMyYB8UBI, libSceGnmDriver , 1 , Ps4_sceGnmDebuggerSetAddressWatch ),
 LIB_FUNCTION("MJG69Q7ti+s, libSceGnmDriver , 1 , Ps4_sceGnmDebuggerWriteGds ),
 LIB_FUNCTION("PaFw9w6f808, libSceGnmDriver , 1 , Ps4_sceGnmDebuggerWriteSqIndirectRegister ),
 LIB_FUNCTION("qpGITzPE+Zc, libSceGnmDriver , 1 , Ps4_sceGnmDebugHardwareStatus ),
 LIB_FUNCTION("PVT+fuoS9gU, libSceGnmDriver , 1 , Ps4_sceGnmDeleteEqEvent ),
 LIB_FUNCTION("UtObDRQiGbs, libSceGnmDriver , 1 , Ps4_sceGnmDestroyWorkloadStream ),
 LIB_FUNCTION("bX5IbRvECXk, libSceGnmDriver , 1 , Ps4_sceGnmDingDong ),
 LIB_FUNCTION("byXlqupd8cE, libSceGnmDriver , 1 , Ps4_sceGnmDingDongForWorkload ),
 LIB_FUNCTION("HHo1BAljZO8, libSceGnmDriver , 1 , Ps4_sceGnmDisableMipStatsReport ),
 LIB_FUNCTION("0BzLGljcwBo, libSceGnmDriver , 1 , Ps4_sceGnmDispatchDirect ),
 LIB_FUNCTION("Z43vKp5k7r0, libSceGnmDriver , 1 , Ps4_sceGnmDispatchIndirect ),
 LIB_FUNCTION("wED4ZXCFJT0, libSceGnmDriver , 1 , Ps4_sceGnmDispatchIndirectOnMec ),
 LIB_FUNCTION("nF6bFRUBRAU, libSceGnmDriver , 1 , Ps4_sceGnmDispatchInitDefaultHardwareState ),
 LIB_FUNCTION("HlTPoZ-oY7Y, libSceGnmDriver , 1 , Ps4_sceGnmDrawIndex ),
 LIB_FUNCTION("GGsn7jMTxw4, libSceGnmDriver , 1 , Ps4_sceGnmDrawIndexAuto ),
 LIB_FUNCTION("ED9-Fjr8Ta4, libSceGnmDriver , 1 , Ps4_sceGnmDrawIndexIndirect ),
 LIB_FUNCTION("thbPcG7E7qk, libSceGnmDriver , 1 , Ps4_sceGnmDrawIndexIndirectCountMulti ),
 LIB_FUNCTION("5q95ravnueg, libSceGnmDriver , 1 , Ps4_sceGnmDrawIndexIndirectMulti ),
 LIB_FUNCTION("jHdPvIzlpKc, libSceGnmDriver , 1 , Ps4_sceGnmDrawIndexMultiInstanced ),
 LIB_FUNCTION("oYM+YzfCm2Y, libSceGnmDriver , 1 , Ps4_sceGnmDrawIndexOffset ),
 LIB_FUNCTION("4v+otIIdjqg, libSceGnmDriver , 1 , Ps4_sceGnmDrawIndirect ),
 LIB_FUNCTION("cUCo8OvArrw, libSceGnmDriver , 1 , Ps4_sceGnmDrawIndirectCountMulti ),
 LIB_FUNCTION("f5QQLp9rzGk, libSceGnmDriver , 1 , Ps4_sceGnmDrawIndirectMulti ),
 LIB_FUNCTION("Idffwf3yh8s, libSceGnmDriver , 1 , Ps4_sceGnmDrawInitDefaultHardwareState ),
 LIB_FUNCTION("QhnyReteJ1M, libSceGnmDriver , 1 , Ps4_sceGnmDrawInitDefaultHardwareState175 ),
 LIB_FUNCTION("0H2vBYbTLHI, libSceGnmDriver , 1 , Ps4_sceGnmDrawInitDefaultHardwareState200 ),
 LIB_FUNCTION("yb2cRhagD1I, libSceGnmDriver , 1 , Ps4_sceGnmDrawInitDefaultHardwareState350 ),
 LIB_FUNCTION("8lH54sfjfmU, libSceGnmDriver , 1 , Ps4_sceGnmDrawInitToDefaultContextState ),
 LIB_FUNCTION("im2ZuItabu4, libSceGnmDriver , 1 , Ps4_sceGnmDrawInitToDefaultContextState400 ),
 LIB_FUNCTION("stDSYW2SBVM, libSceGnmDriver , 1 , Ps4_sceGnmDrawOpaqueAuto ),
 LIB_FUNCTION("TLV4mswiZ4A, libSceGnmDriver , 1 , Ps4_sceGnmDriverCaptureInProgress ),
 LIB_FUNCTION("ODEeJ1GfDtE, libSceGnmDriver , 1 , Ps4_sceGnmDriverInternalRetrieveGnmInterface ),
 LIB_FUNCTION("4LSXsEKPTsE, libSceGnmDriver , 1 , Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForGpuDebugger ),
 LIB_FUNCTION("MpncRjHNYRE, libSceGnmDriver , 1 , Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForGpuException ),
 LIB_FUNCTION("EwjWGcIOgeM, libSceGnmDriver , 1 , Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForHDRScopes ),
 LIB_FUNCTION("3EXdrVC7WFk, libSceGnmDriver , 1 , Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForReplay ),
 LIB_FUNCTION("P9iKqxAGeck, libSceGnmDriver , 1 , Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForResourceRegistration ),
 LIB_FUNCTION("t-vIc5cTEzg, libSceGnmDriver , 1 , Ps4_sceGnmDriverInternalRetrieveGnmInterfaceForValidation ),
 LIB_FUNCTION("BvvO8Up88Zc, libSceGnmDriver , 1 , Ps4_sceGnmDriverInternalVirtualQuery ),
 LIB_FUNCTION("R6z1xM3pW-w, libSceGnmDriver , 1 , Ps4_sceGnmDriverTraceInProgress ),
 LIB_FUNCTION("d88anrgNoKY, libSceGnmDriver , 1 , Ps4_sceGnmDriverTriggerCapture ),
 LIB_FUNCTION("Fa3x75OOLRA, libSceGnmDriver , 1 , Ps4_sceGnmEndWorkload ),
 LIB_FUNCTION("4Mv9OXypBG8, libSceGnmDriver , 1 , Ps4_sceGnmFindResourcesPublic ),
 LIB_FUNCTION("iBt3Oe00Kvc, libSceGnmDriver , 1 , Ps4_sceGnmFlushGarlic ),
 LIB_FUNCTION("GviyYfFQIkc, libSceGnmDriver , 1 , Ps4_sceGnmGetCoredumpAddress ),
 LIB_FUNCTION("meiO-5ZCVIE, libSceGnmDriver , 1 , Ps4_sceGnmGetCoredumpMode ),
 LIB_FUNCTION("O-7nHKgcNSQ, libSceGnmDriver , 1 , Ps4_sceGnmGetCoredumpProtectionFaultTimestamp ),
 LIB_FUNCTION("bSJFzejYrJI, libSceGnmDriver , 1 , Ps4_sceGnmGetDbgGcHandle ),
 LIB_FUNCTION("pd4C7da6sEg, libSceGnmDriver , 1 , Ps4_sceGnmGetDebugTimestamp ),
 LIB_FUNCTION("UoYY0DWMC0U, libSceGnmDriver , 1 , Ps4_sceGnmGetEqEventType ),
 LIB_FUNCTION("H7-fgvEutM0, libSceGnmDriver , 1 , Ps4_sceGnmGetEqTimeStamp ),
 LIB_FUNCTION("oL4hGI1PMpw, libSceGnmDriver , 1 , Ps4_sceGnmGetGpuBlockStatus ),
 LIB_FUNCTION("Fwvh++m9IQI, libSceGnmDriver , 1 , Ps4_sceGnmGetGpuCoreClockFrequency ),
 LIB_FUNCTION("tZCSL5ulnB4, libSceGnmDriver , 1 , Ps4_sceGnmGetGpuInfoStatus ),
 LIB_FUNCTION("iFirFzgYsvw, libSceGnmDriver , 1 , Ps4_sceGnmGetLastWaitedAddress ),
 LIB_FUNCTION("KnldROUkWJY, libSceGnmDriver , 1 , Ps4_sceGnmGetNumTcaUnits ),
 LIB_FUNCTION("FFVZcCu3zWU, libSceGnmDriver , 1 , Ps4_sceGnmGetOffChipTessellationBufferSize ),
 LIB_FUNCTION("QJjPjlmPAL0, libSceGnmDriver , 1 , Ps4_sceGnmGetOwnerName ),
 LIB_FUNCTION("dewXw5roLs0, libSceGnmDriver , 1 , Ps4_sceGnmGetPhysicalCounterFromVirtualized ),
 LIB_FUNCTION("fzJdEihTFV4, libSceGnmDriver , 1 , Ps4_sceGnmGetProtectionFaultTimeStamp ),
 LIB_FUNCTION("4PKnYXOhcx4, libSceGnmDriver , 1 , Ps4_sceGnmGetResourceBaseAddressAndSizeInBytes ),
 LIB_FUNCTION("O0S96YnD04U, libSceGnmDriver , 1 , Ps4_sceGnmGetResourceName ),
 LIB_FUNCTION("UBv7FkVfzcQ, libSceGnmDriver , 1 , Ps4_sceGnmGetResourceShaderGuid ),
 LIB_FUNCTION("bdqdvIkLPIU, libSceGnmDriver , 1 , Ps4_sceGnmGetResourceType ),
 LIB_FUNCTION("UoBuWAhKk7U, libSceGnmDriver , 1 , Ps4_sceGnmGetResourceUserData ),
 LIB_FUNCTION("nEyFbYUloIM, libSceGnmDriver , 1 , Ps4_sceGnmGetShaderProgramBaseAddress ),
 LIB_FUNCTION("k7iGTvDQPLQ, libSceGnmDriver , 1 , Ps4_sceGnmGetShaderStatus ),
 LIB_FUNCTION("ln33zjBrfjk, libSceGnmDriver , 1 , Ps4_sceGnmGetTheTessellationFactorRingBufferBaseAddress ),
 LIB_FUNCTION("QLdG7G-PBZo, libSceGnmDriver , 1 , Ps4_sceGnmGpuPaDebugEnter ),
 LIB_FUNCTION("tVEdZe3wlbY, libSceGnmDriver , 1 , Ps4_sceGnmGpuPaDebugLeave ),
 LIB_FUNCTION("NfvOrNzy6sk, libSceGnmDriver , 1 , Ps4_sceGnmInsertDingDongMarker ),
 LIB_FUNCTION("7qZVNgEu+SY, libSceGnmDriver , 1 , Ps4_sceGnmInsertPopMarker ),
 LIB_FUNCTION("aPIZJTXC+cU, libSceGnmDriver , 1 , Ps4_sceGnmInsertPushColorMarker ),
 LIB_FUNCTION("W1Etj-jlW7Y, libSceGnmDriver , 1 , Ps4_sceGnmInsertPushMarker ),
 LIB_FUNCTION("aj3L-iaFmyk, libSceGnmDriver , 1 , Ps4_sceGnmInsertSetColorMarker ),
 LIB_FUNCTION("jiItzS6+22g, libSceGnmDriver , 1 , Ps4_sceGnmInsertSetMarker ),
 LIB_FUNCTION("URDgJcXhQOs, libSceGnmDriver , 1 , Ps4_sceGnmInsertThreadTraceMarker ),
 LIB_FUNCTION("1qXLHIpROPE, libSceGnmDriver , 1 , Ps4_sceGnmInsertWaitFlipDone ),
 LIB_FUNCTION("HRyNHoAjb6E, libSceGnmDriver , 1 , Ps4_sceGnmIsCoredumpValid ),
 LIB_FUNCTION("jg33rEKLfVs, libSceGnmDriver , 1 , Ps4_sceGnmIsUserPaEnabled ),
 LIB_FUNCTION("26PM5Mzl8zc, libSceGnmDriver , 1 , Ps4_sceGnmLogicalCuIndexToPhysicalCuIndex ),
 LIB_FUNCTION("RU74kek-N0c, libSceGnmDriver , 1 , Ps4_sceGnmLogicalCuMaskToPhysicalCuMask ),
 LIB_FUNCTION("Kl0Z3LH07QI, libSceGnmDriver , 1 , Ps4_sceGnmLogicalTcaUnitToPhysical ),
 LIB_FUNCTION("29oKvKXzEZo, libSceGnmDriver , 1 , Ps4_sceGnmMapComputeQueue ),
 LIB_FUNCTION("A+uGq+3KFtQ, libSceGnmDriver , 1 , Ps4_sceGnmMapComputeQueueWithPriority ),
 LIB_FUNCTION("+N+wrSYBLIw, libSceGnmDriver , 1 , Ps4_sceGnmPaDisableFlipCallbacks ),
 LIB_FUNCTION("8WDA9RiXLaw, libSceGnmDriver , 1 , Ps4_sceGnmPaEnableFlipCallbacks ),
 LIB_FUNCTION("tNuT48mApTc, libSceGnmDriver , 1 , Ps4_sceGnmPaHeartbeat ),
 LIB_FUNCTION("6IMbpR7nTzA, libSceGnmDriver , 1 , Ps4_sceGnmQueryResourceRegistrationUserMemoryRequirements ),
 LIB_FUNCTION("+rJnw2e9O+0, libSceGnmDriver , 1 , Ps4_sceGnmRaiseUserExceptionEvent ),
 LIB_FUNCTION("9Mv61HaMhfA, libSceGnmDriver , 1 , Ps4_sceGnmRegisterGdsResource ),
 LIB_FUNCTION("t7-VbMosbR4, libSceGnmDriver , 1 , Ps4_sceGnmRegisterGnmLiveCallbackConfig ),
 LIB_FUNCTION("ZFqKFl23aMc, libSceGnmDriver , 1 , Ps4_sceGnmRegisterOwner ),
 LIB_FUNCTION("nvEwfYAImTs, libSceGnmDriver , 1 , Ps4_sceGnmRegisterResource ),
 LIB_FUNCTION("gObODli-OH8, libSceGnmDriver , 1 , Ps4_sceGnmRequestFlipAndSubmitDone ),
 LIB_FUNCTION("6YRHhh5mHCs, libSceGnmDriver , 1 , Ps4_sceGnmRequestFlipAndSubmitDoneForWorkload ),
 LIB_FUNCTION("f85orjx7qts, libSceGnmDriver , 1 , Ps4_sceGnmRequestMipStatsReportAndReset ),
 LIB_FUNCTION("MYRtYhojKdA, libSceGnmDriver , 1 , Ps4_sceGnmResetVgtControl ),
 LIB_FUNCTION("hS0MKPRdNr0, libSceGnmDriver , 1 , Ps4_sceGnmSdmaClose ),
 LIB_FUNCTION("31G6PB2oRYQ, libSceGnmDriver , 1 , Ps4_sceGnmSdmaConstFill ),
 LIB_FUNCTION("Lg2isla2XeQ, libSceGnmDriver , 1 , Ps4_sceGnmSdmaCopyLinear ),
 LIB_FUNCTION("-Se2FY+UTsI, libSceGnmDriver , 1 , Ps4_sceGnmSdmaCopyTiled ),
 LIB_FUNCTION("OlFgKnBsALE, libSceGnmDriver , 1 , Ps4_sceGnmSdmaCopyWindow ),
 LIB_FUNCTION("LQQN0SwQv8c, libSceGnmDriver , 1 , Ps4_sceGnmSdmaFlush ),
 LIB_FUNCTION("suUlSjWr7CE, libSceGnmDriver , 1 , Ps4_sceGnmSdmaGetMinCmdSize ),
 LIB_FUNCTION("5AtqyMgO7fM, libSceGnmDriver , 1 , Ps4_sceGnmSdmaOpen ),
 LIB_FUNCTION("KXltnCwEJHQ, libSceGnmDriver , 1 , Ps4_sceGnmSetCsShader ),
 LIB_FUNCTION("Kx-h-nWQJ8A, libSceGnmDriver , 1 , Ps4_sceGnmSetCsShaderWithModifier ),
 LIB_FUNCTION("X9Omw9dwv5M, libSceGnmDriver , 1 , Ps4_sceGnmSetEmbeddedPsShader ),
 LIB_FUNCTION("+AFvOEXrKJk, libSceGnmDriver , 1 , Ps4_sceGnmSetEmbeddedVsShader ),
 LIB_FUNCTION("FUHG8sQ3R58, libSceGnmDriver , 1 , Ps4_sceGnmSetEsShader ),
 LIB_FUNCTION("jtkqXpAOY6w, libSceGnmDriver , 1 , Ps4_sceGnmSetGsRingSizes ),
 LIB_FUNCTION("UJwNuMBcUAk, libSceGnmDriver , 1 , Ps4_sceGnmSetGsShader ),
 LIB_FUNCTION("VJNjFtqiF5w, libSceGnmDriver , 1 , Ps4_sceGnmSetHsShader ),
 LIB_FUNCTION("vckdzbQ46SI, libSceGnmDriver , 1 , Ps4_sceGnmSetLsShader ),
 LIB_FUNCTION("bQVd5YzCal0, libSceGnmDriver , 1 , Ps4_sceGnmSetPsShader ),
 LIB_FUNCTION("5uFKckiJYRM, libSceGnmDriver , 1 , Ps4_sceGnmSetPsShader350 ),
 LIB_FUNCTION("q-qhDxP67Hg, libSceGnmDriver , 1 , Ps4_sceGnmSetResourceRegistrationUserMemory ),
 LIB_FUNCTION("K3BKBBYKUSE, libSceGnmDriver , 1 , Ps4_sceGnmSetResourceUserData ),
 LIB_FUNCTION("0O3xxFaiObw, libSceGnmDriver , 1 , Ps4_sceGnmSetSpiEnableSqCounters ),
 LIB_FUNCTION("lN7Gk-p9u78, libSceGnmDriver , 1 , Ps4_sceGnmSetSpiEnableSqCountersForUnitInstance ),
 LIB_FUNCTION("+xuDhxlWRPg, libSceGnmDriver , 1 , Ps4_sceGnmSetupMipStatsReport ),
 LIB_FUNCTION("cFCp0NX8wf0, libSceGnmDriver , 1 , Ps4_sceGnmSetVgtControl ),
 LIB_FUNCTION("gAhCn6UiU4Y, libSceGnmDriver , 1 , Ps4_sceGnmSetVsShader ),
 LIB_FUNCTION("y+iI2lkX+qI, libSceGnmDriver , 1 , Ps4_sceGnmSetWaveLimitMultiplier ),
 LIB_FUNCTION("XiyzNZ9J4nQ, libSceGnmDriver , 1 , Ps4_sceGnmSetWaveLimitMultipliers ),
 LIB_FUNCTION("kkn+iy-mhyg, libSceGnmDriver , 1 , Ps4_sceGnmSpmEndSpm ),
 LIB_FUNCTION("aqhuK2Mj4X4, libSceGnmDriver , 1 , Ps4_sceGnmSpmInit ),
 LIB_FUNCTION("KHpZ9hJo1c0, libSceGnmDriver , 1 , Ps4_sceGnmSpmInit2 ),
 LIB_FUNCTION("QEsMC+M3yjE, libSceGnmDriver , 1 , Ps4_sceGnmSpmSetDelay ),
 LIB_FUNCTION("hljMAxTLNF0, libSceGnmDriver , 1 , Ps4_sceGnmSpmSetMuxRam ),
 LIB_FUNCTION("bioGsp74SLM, libSceGnmDriver , 1 , Ps4_sceGnmSpmSetMuxRam2 ),
 LIB_FUNCTION("cMWWYeqQQlM, libSceGnmDriver , 1 , Ps4_sceGnmSpmSetSelectCounter ),
 LIB_FUNCTION("-zJi8Vb4Du4, libSceGnmDriver , 1 , Ps4_sceGnmSpmSetSpmSelects ),
 LIB_FUNCTION("xTsOqp-1bE4, libSceGnmDriver , 1 , Ps4_sceGnmSpmSetSpmSelects2 ),
 LIB_FUNCTION("AmmYLcJGTl0, libSceGnmDriver , 1 , Ps4_sceGnmSpmStartSpm ),
 LIB_FUNCTION("UHDiSFDxNao, libSceGnmDriver , 1 , Ps4_sceGnmSqttFini ),
 LIB_FUNCTION("a3tLC56vwug, libSceGnmDriver , 1 , Ps4_sceGnmSqttFinishTrace ),
 LIB_FUNCTION("L-owl1dSKKg, libSceGnmDriver , 1 , Ps4_sceGnmSqttGetBcInfo ),
 LIB_FUNCTION("LQtzqghKQm4, libSceGnmDriver , 1 , Ps4_sceGnmSqttGetGpuClocks ),
 LIB_FUNCTION("wYN5mmv6Ya8, libSceGnmDriver , 1 , Ps4_sceGnmSqttGetHiWater ),
 LIB_FUNCTION("9X4SkENMS0M, libSceGnmDriver , 1 , Ps4_sceGnmSqttGetStatus ),
 LIB_FUNCTION("lbMccQM2iqc, libSceGnmDriver , 1 , Ps4_sceGnmSqttGetTraceCounter ),
 LIB_FUNCTION("DYAC6JUeZvM, libSceGnmDriver , 1 , Ps4_sceGnmSqttGetTraceWptr ),
 LIB_FUNCTION("pS2tjBxzJr4, libSceGnmDriver , 1 , Ps4_sceGnmSqttGetWrapCounts ),
 LIB_FUNCTION("rXV8az6X+fM, libSceGnmDriver , 1 , Ps4_sceGnmSqttGetWrapCounts2 ),
 LIB_FUNCTION("ARS+TNLopyk, libSceGnmDriver , 1 , Ps4_sceGnmSqttGetWritebackLabels ),
 LIB_FUNCTION("X6yCBYPP7HA, libSceGnmDriver , 1 , Ps4_sceGnmSqttInit ),
 LIB_FUNCTION("2IJhUyK8moE, libSceGnmDriver , 1 , Ps4_sceGnmSqttSelectMode ),
 LIB_FUNCTION("QA5h6Gh3r60, libSceGnmDriver , 1 , Ps4_sceGnmSqttSelectTarget ),
 LIB_FUNCTION("F5XJY1XHa3Y, libSceGnmDriver , 1 , Ps4_sceGnmSqttSelectTokens ),
 LIB_FUNCTION("wJtaTpNZfH4, libSceGnmDriver , 1 , Ps4_sceGnmSqttSetCuPerfMask ),
 LIB_FUNCTION("kY4dsQh+SH4, libSceGnmDriver , 1 , Ps4_sceGnmSqttSetDceEventWrite ),
 LIB_FUNCTION("7XRH1CIfNpI, libSceGnmDriver , 1 , Ps4_sceGnmSqttSetHiWater ),
 LIB_FUNCTION("05YzC2r3hHo, libSceGnmDriver , 1 , Ps4_sceGnmSqttSetTraceBuffer2 ),
 LIB_FUNCTION("ASUric-2EnI, libSceGnmDriver , 1 , Ps4_sceGnmSqttSetTraceBuffers ),
 LIB_FUNCTION("gPxYzPp2wlo, libSceGnmDriver , 1 , Ps4_sceGnmSqttSetUserData ),
 LIB_FUNCTION("d-YcZX7SIQA, libSceGnmDriver , 1 , Ps4_sceGnmSqttSetUserdataTimer ),
 LIB_FUNCTION("ru8cb4he6O8, libSceGnmDriver , 1 , Ps4_sceGnmSqttStartTrace ),
 LIB_FUNCTION("gVuGo1nBnG8, libSceGnmDriver , 1 , Ps4_sceGnmSqttStopTrace ),
 LIB_FUNCTION("OpyolX6RwS0, libSceGnmDriver , 1 , Ps4_sceGnmSqttSwitchTraceBuffer ),
 LIB_FUNCTION("dl5u5eGBgNk, libSceGnmDriver , 1 , Ps4_sceGnmSqttSwitchTraceBuffer2 ),
 LIB_FUNCTION("QLzOwOF0t+A, libSceGnmDriver , 1 , Ps4_sceGnmSqttWaitForEvent ),
 LIB_FUNCTION("xbxNatawohc, libSceGnmDriver , 1 , Ps4_sceGnmSubmitAndFlipCommandBuffers ),
 LIB_FUNCTION("Ga6r7H6Y0RI, libSceGnmDriver , 1 , Ps4_sceGnmSubmitAndFlipCommandBuffersForWorkload ),
 LIB_FUNCTION("zwY0YV91TTI, libSceGnmDriver , 1 , Ps4_sceGnmSubmitCommandBuffers ),
 LIB_FUNCTION("jRcI8VcgTz4, libSceGnmDriver , 1 , Ps4_sceGnmSubmitCommandBuffersForWorkload ),
 LIB_FUNCTION("yvZ73uQUqrk, libSceGnmDriver , 1 , Ps4_sceGnmSubmitDone ),
 LIB_FUNCTION("ArSg-TGinhk, libSceGnmDriver , 1 , Ps4_sceGnmUnmapComputeQueue ),
 LIB_FUNCTION("yhFCnaz5daw, libSceGnmDriver , 1 , Ps4_sceGnmUnregisterAllResourcesForOwner ),
 LIB_FUNCTION("fhKwCVVj9nk, libSceGnmDriver , 1 , Ps4_sceGnmUnregisterOwnerAndResources ),
 LIB_FUNCTION("k8EXkhIP+lM, libSceGnmDriver , 1 , Ps4_sceGnmUnregisterResource ),
 LIB_FUNCTION("nLM2i2+65hA, libSceGnmDriver , 1 , Ps4_sceGnmUpdateGsShader ),
 LIB_FUNCTION("GNlx+y7xPdE, libSceGnmDriver , 1 , Ps4_sceGnmUpdateHsShader ),
 LIB_FUNCTION("4MgRw-bVNQU, libSceGnmDriver , 1 , Ps4_sceGnmUpdatePsShader ),
 LIB_FUNCTION("mLVL7N7BVBg, libSceGnmDriver , 1 , Ps4_sceGnmUpdatePsShader350 ),
 LIB_FUNCTION("V31V01UiScY, libSceGnmDriver , 1 , Ps4_sceGnmUpdateVsShader ),
 LIB_FUNCTION("iCO804ZgzdA, libSceGnmDriver , 1 , Ps4_sceGnmValidateCommandBuffers ),
 LIB_FUNCTION("SXw4dZEkgpA, libSceGnmDriver , 1 , Ps4_sceGnmValidateDisableDiagnostics ),
 LIB_FUNCTION("BgM3t3LvcNk, libSceGnmDriver , 1 , Ps4_sceGnmValidateDisableDiagnostics2 ),
 LIB_FUNCTION("qGP74T5OWJc, libSceGnmDriver , 1 , Ps4_sceGnmValidateDispatchCommandBuffers ),
 LIB_FUNCTION("hsZPf1lON7E, libSceGnmDriver , 1 , Ps4_sceGnmValidateDrawCommandBuffers ),
 LIB_FUNCTION("RX7XCNSaL6I, libSceGnmDriver , 1 , Ps4_sceGnmValidateGetDiagnosticInfo ),
 LIB_FUNCTION("5SHGNwLXBV4, libSceGnmDriver , 1 , Ps4_sceGnmValidateGetDiagnostics ),
 LIB_FUNCTION("HzMN7ANqYEc, libSceGnmDriver , 1 , Ps4_sceGnmValidateGetVersion ),
 LIB_FUNCTION("rTIV11nMQuM, libSceGnmDriver , 1 , Ps4_sceGnmValidateOnSubmitEnabled ),
 LIB_FUNCTION("MBMa6EFu4Ko, libSceGnmDriver , 1 , Ps4_sceGnmValidateResetState ),
 LIB_FUNCTION("Q7t4VEYLafI, libSceGnmDriver , 1 , Ps4_sceGnmValidationRegisterMemoryCheckCallback ),
 LIB_FUNCTION("xeTLfxVIQO4, libSceGnmDriver , 1 , Ps4_sceRazorCaptureCommandBuffersOnlyImmediate ),
 LIB_FUNCTION("9thMn+uB1is, libSceGnmDriver , 1 , Ps4_sceRazorCaptureCommandBuffersOnlySinceLastFlip ),
 LIB_FUNCTION("u9YKpRRHe-M, libSceGnmDriver , 1 , Ps4_sceRazorCaptureImmediate ),
 LIB_FUNCTION("4UFagYlfuAM, libSceGnmDriver , 1 , Ps4_sceRazorCaptureSinceLastFlip ),
 LIB_FUNCTION("f33OrruQYbM, libSceGnmDriver , 1 , Ps4_sceRazorIsLoaded ),
 LIB_FUNCTION("Bj0GWi1jWcM, libSceGnmDriver , 1 , Ps4_FuncBj0GWi1jWcM ),
 LIB_FUNCTION("DKusr7JYQp0, libSceGnmDriver , 1 , Ps4_FuncDKusr7JYQp0 ),
 LIB_FUNCTION("FQzzNvwumaM, libSceGnmDriver , 1 , Ps4_FuncFQzzNvwumaM ),
 LIB_FUNCTION("F8pof57lLUk, libSceGnmDriver , 1 , Ps4_FuncF8pof57lLUk ),
 LIB_FUNCTION("GHC4n3Wca0U, libSceGnmDriver , 1 , Ps4_FuncGHC4n3Wca0U ),
 LIB_FUNCTION("JvkCnvaKlV4, libSceGnmDriver , 1 , Ps4_FuncJvkCnvaKlV4 ),
 LIB_FUNCTION("MB49u6sJLbA, libSceGnmDriver , 1 , Ps4_FuncMB49u6sJLbA ),
 LIB_FUNCTION("MLr+Fyrxf+8, libSceGnmDriver , 1 , Ps4_FuncMLr+Fyrxf+8 ),
 LIB_FUNCTION("Pmo+ggPZUxc, libSceGnmDriver , 1 , Ps4_FuncPmo+ggPZUxc ),
 LIB_FUNCTION("QP7vDGU0xDQ, libSceGnmDriver , 1 , Ps4_FuncQP7vDGU0xDQ ),
 LIB_FUNCTION("QWuQed5Mus4, libSceGnmDriver , 1 , Ps4_FuncQWuQed5Mus4 ),
 LIB_FUNCTION("R3TYO7Tdv5o, libSceGnmDriver , 1 , Ps4_FuncR3TYO7Tdv5o ),
 LIB_FUNCTION("UGePHM7rmgA, libSceGnmDriver , 1 , Ps4_FuncUGePHM7rmgA ),
 LIB_FUNCTION("VKLsX6TGJBM, libSceGnmDriver , 1 , Ps4_FuncVKLsX6TGJBM ),
 LIB_FUNCTION("WpxSyDE4rms, libSceGnmDriver , 1 , Ps4_FuncWpxSyDE4rms ),
 LIB_FUNCTION("XSIZOjHqEUI, libSceGnmDriver , 1 , Ps4_FuncXSIZOjHqEUI ),
 LIB_FUNCTION("clo23rtglI0, libSceGnmDriver , 1 , Ps4_Funcclo23rtglI0 ),
 LIB_FUNCTION("gCGlAvphubs, libSceGnmDriver , 1 , Ps4_FuncgCGlAvphubs ),
 LIB_FUNCTION("nQAv4PpA8OY, libSceGnmDriver , 1 , Ps4_FuncnQAv4PpA8OY ),
 LIB_FUNCTION("nSl-NqcCi3E, libSceGnmDriver , 1 , Ps4_FuncnSl-NqcCi3E ),
 LIB_FUNCTION("otfsenvPebM, libSceGnmDriver , 1 , Ps4_FuncotfsenvPebM ),
 LIB_FUNCTION("qhKjy4mQhUo, libSceGnmDriver , 1 , Ps4_FuncqhKjy4mQhUo ),
 LIB_FUNCTION("rcjdwAUCC8Y, libSceGnmDriver , 1 , Ps4_FuncrcjdwAUCC8Y ),
 LIB_FUNCTION("sKhoi2ectC0, libSceGnmDriver , 1 , Ps4_FuncsKhoi2ectC0 ),
 LIB_FUNCTION("tIkCC1FXpf8, libSceGnmDriver , 1 , Ps4_FunctIkCC1FXpf8 ),
 LIB_FUNCTION("ut57TBmRQN0, libSceGnmDriver , 1 , Ps4_Funcut57TBmRQN0 ),
 LIB_FUNCTION("0VEbnc-7Pdk, libSceGnmDriver , 1 , Ps4_Func0VEbnc-7Pdk ),
 LIB_FUNCTION("1TRGZJsC5Y4, libSceGnmDriver , 1 , Ps4_Func1TRGZJsC5Y4 ),
 LIB_FUNCTION("2Lbo4o4e8KM, libSceGnmDriver , 1 , Ps4_Func2Lbo4o4e8KM ),
 LIB_FUNCTION("2T1zOhnddFQ, libSceGnmDriver , 1 , Ps4_Func2T1zOhnddFQ ),
 LIB_FUNCTION("3plUQ7wqgxc, libSceGnmDriver , 1 , Ps4_Func3plUQ7wqgxc ),
 LIB_FUNCTION("326VKBUMI-8, libSceGnmDriver , 1 , Ps4_Func326VKBUMI-8 ),
 LIB_FUNCTION("7LTGukH+M1A, libSceGnmDriver , 1 , Ps4_Func7LTGukH+M1A ),
 LIB_FUNCTION("dqPBvjFVpTA, libSceGnmDebugModuleReset , 1 , Ps4_sceGnmDebugModuleReset ),
 LIB_FUNCTION("RNPAItiMLIg, libSceGnmDebugReset , 1 , Ps4_sceGnmDebugReset ),
 LIB_FUNCTION("xMMot887QXE, libSceGnmDebugReset , 1 , Ps4_FuncxMMot887QXE ),
 LIB_FUNCTION("pF1HQjbmQJ0, libSceGnmDriverCompat , 1 , Ps4_sceGnmDrawInitToDefaultContextStateInternalCommand ),
 LIB_FUNCTION("jajhf-Gi3AI, libSceGnmDriverCompat , 1 , Ps4_sceGnmDrawInitToDefaultContextStateInternalSize ),
 LIB_FUNCTION("vbcR4Ken6AA, libSceGnmDriverResourceRegistration , 1 , Ps4_sceGnmFindResources ),
 LIB_FUNCTION("eLQbNsKeTkU, libSceGnmDriverResourceRegistration , 1 , Ps4_sceGnmGetResourceRegistrationBuffers ),
 LIB_FUNCTION("j6mSQs3UgaY, libSceGnmDriverResourceRegistration , 1 , Ps4_sceGnmRegisterOwnerForSystem ),
 LIB_FUNCTION("HEOIaxbuVTA, libSceGnmDriverResourceRegistration , 1 , Ps4_FuncHEOIaxbuVTA ),
 LIB_FUNCTION("gQNwGezNDgE, libSceGnmDriverResourceRegistration , 1 , Ps4_FuncgQNwGezNDgE ),
 LIB_FUNCTION("v7QcBXR48L8, libSceGnmDriverResourceRegistration , 1 , Ps4_Funcv7QcBXR48L8 ),
 LIB_FUNCTION("5R1E24FRI4w, libSceGnmDriverResourceRegistration , 1 , Ps4_Func5R1E24FRI4w ),
 LIB_FUNCTION("+RaJBCVJZVM, libSceGnmDriverResourceRegistration , 1 , Ps4_Func+RaJBCVJZVM ),
 LIB_FUNCTION("Fwvh++m9IQI, libSceGnmGetGpuCoreClockFrequency , 1 , Ps4_sceGnmGetGpuCoreClockFrequency ),
 LIB_FUNCTION("R3TYO7Tdv5o, libSceGnmWaitFreeSubmit , 1 , Ps4_FuncR3TYO7Tdv5o ),
 LIB_FUNCTION("ut57TBmRQN0, libSceGnmWaitFreeSubmit , 1 , Ps4_Funcut57TBmRQN0 ),
};

