//Generated By moduleGenerator
#include "libSceGnmDriver.h"
#include "common/log.h"
#include "error_codes.h"

namespace Libraries::libSceGnmDriver{

int PS4_SYSV_ABI sceGnmAddEqEvent(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmAddEqEvent");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmAreSubmitsAllowed(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmAreSubmitsAllowed");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmBeginWorkload(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmBeginWorkload");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmComputeWaitOnAddress(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmComputeWaitOnAddress");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmComputeWaitSemaphore(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmComputeWaitSemaphore");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmCreateWorkloadStream(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmCreateWorkloadStream");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerGetAddressWatch(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDebuggerGetAddressWatch");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerHaltWavefront(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDebuggerHaltWavefront");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerReadGds(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDebuggerReadGds");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerReadSqIndirectRegister(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDebuggerReadSqIndirectRegister");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerResumeWavefront(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDebuggerResumeWavefront");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerResumeWavefrontCreation(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDebuggerResumeWavefrontCreation");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerSetAddressWatch(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDebuggerSetAddressWatch");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerWriteGds(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDebuggerWriteGds");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebuggerWriteSqIndirectRegister(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDebuggerWriteSqIndirectRegister");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebugHardwareStatus(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDebugHardwareStatus");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDeleteEqEvent(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDeleteEqEvent");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDestroyWorkloadStream(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDestroyWorkloadStream");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDingDong(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDingDong");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDingDongForWorkload(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDingDongForWorkload");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDisableMipStatsReport(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDisableMipStatsReport");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDispatchDirect(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDispatchDirect");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDispatchIndirect(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDispatchIndirect");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDispatchIndirectOnMec(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDispatchIndirectOnMec");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDispatchInitDefaultHardwareState(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDispatchInitDefaultHardwareState");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndex(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawIndex");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndexAuto(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawIndexAuto");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndexIndirect(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawIndexIndirect");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndexIndirectCountMulti(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawIndexIndirectCountMulti");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndexIndirectMulti(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawIndexIndirectMulti");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndexMultiInstanced(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawIndexMultiInstanced");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndexOffset(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawIndexOffset");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndirect(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawIndirect");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndirectCountMulti(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawIndirectCountMulti");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawIndirectMulti(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawIndirectMulti");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitDefaultHardwareState(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawInitDefaultHardwareState");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitDefaultHardwareState175(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawInitDefaultHardwareState175");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitDefaultHardwareState200(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawInitDefaultHardwareState200");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitDefaultHardwareState350(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawInitDefaultHardwareState350");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitToDefaultContextState(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawInitToDefaultContextState");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitToDefaultContextState400(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawInitToDefaultContextState400");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawOpaqueAuto(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawOpaqueAuto");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverCaptureInProgress(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDriverCaptureInProgress");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalRetrieveGnmInterface(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDriverInternalRetrieveGnmInterface");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalRetrieveGnmInterfaceForGpuDebugger(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDriverInternalRetrieveGnmInterfaceForGpuDebugger");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalRetrieveGnmInterfaceForGpuException(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDriverInternalRetrieveGnmInterfaceForGpuException");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalRetrieveGnmInterfaceForHDRScopes(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDriverInternalRetrieveGnmInterfaceForHDRScopes");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalRetrieveGnmInterfaceForReplay(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDriverInternalRetrieveGnmInterfaceForReplay");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalRetrieveGnmInterfaceForResourceRegistration(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDriverInternalRetrieveGnmInterfaceForResourceRegistration");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalRetrieveGnmInterfaceForValidation(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDriverInternalRetrieveGnmInterfaceForValidation");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverInternalVirtualQuery(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDriverInternalVirtualQuery");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverTraceInProgress(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDriverTraceInProgress");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDriverTriggerCapture(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDriverTriggerCapture");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmEndWorkload(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmEndWorkload");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmFindResourcesPublic(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmFindResourcesPublic");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmFlushGarlic(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmFlushGarlic");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetCoredumpAddress(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetCoredumpAddress");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetCoredumpMode(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetCoredumpMode");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetCoredumpProtectionFaultTimestamp(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetCoredumpProtectionFaultTimestamp");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetDbgGcHandle(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetDbgGcHandle");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetDebugTimestamp(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetDebugTimestamp");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetEqEventType(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetEqEventType");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetEqTimeStamp(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetEqTimeStamp");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetGpuBlockStatus(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetGpuBlockStatus");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetGpuCoreClockFrequency(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetGpuCoreClockFrequency");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetGpuInfoStatus(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetGpuInfoStatus");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetLastWaitedAddress(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetLastWaitedAddress");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetNumTcaUnits(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetNumTcaUnits");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetOffChipTessellationBufferSize(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetOffChipTessellationBufferSize");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetOwnerName(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetOwnerName");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetPhysicalCounterFromVirtualized(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetPhysicalCounterFromVirtualized");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetProtectionFaultTimeStamp(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetProtectionFaultTimeStamp");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetResourceBaseAddressAndSizeInBytes(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetResourceBaseAddressAndSizeInBytes");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetResourceName(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetResourceName");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetResourceShaderGuid(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetResourceShaderGuid");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetResourceType(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetResourceType");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetResourceUserData(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetResourceUserData");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetShaderProgramBaseAddress(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetShaderProgramBaseAddress");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetShaderStatus(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetShaderStatus");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetTheTessellationFactorRingBufferBaseAddress(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetTheTessellationFactorRingBufferBaseAddress");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGpuPaDebugEnter(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGpuPaDebugEnter");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGpuPaDebugLeave(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGpuPaDebugLeave");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertDingDongMarker(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmInsertDingDongMarker");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertPopMarker(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmInsertPopMarker");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertPushColorMarker(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmInsertPushColorMarker");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertPushMarker(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmInsertPushMarker");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertSetColorMarker(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmInsertSetColorMarker");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertSetMarker(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmInsertSetMarker");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertThreadTraceMarker(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmInsertThreadTraceMarker");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmInsertWaitFlipDone(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmInsertWaitFlipDone");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmIsCoredumpValid(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmIsCoredumpValid");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmIsUserPaEnabled(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmIsUserPaEnabled");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmLogicalCuIndexToPhysicalCuIndex(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmLogicalCuIndexToPhysicalCuIndex");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmLogicalCuMaskToPhysicalCuMask(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmLogicalCuMaskToPhysicalCuMask");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmLogicalTcaUnitToPhysical(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmLogicalTcaUnitToPhysical");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmMapComputeQueue(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmMapComputeQueue");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmMapComputeQueueWithPriority(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmMapComputeQueueWithPriority");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmPaDisableFlipCallbacks(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmPaDisableFlipCallbacks");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmPaEnableFlipCallbacks(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmPaEnableFlipCallbacks");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmPaHeartbeat(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmPaHeartbeat");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmQueryResourceRegistrationUserMemoryRequirements(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmQueryResourceRegistrationUserMemoryRequirements");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRaiseUserExceptionEvent(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmRaiseUserExceptionEvent");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRegisterGdsResource(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmRegisterGdsResource");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRegisterGnmLiveCallbackConfig(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmRegisterGnmLiveCallbackConfig");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRegisterOwner(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmRegisterOwner");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRegisterResource(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmRegisterResource");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRequestFlipAndSubmitDone(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmRequestFlipAndSubmitDone");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRequestFlipAndSubmitDoneForWorkload(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmRequestFlipAndSubmitDoneForWorkload");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRequestMipStatsReportAndReset(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmRequestMipStatsReportAndReset");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmResetVgtControl(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmResetVgtControl");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaClose(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSdmaClose");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaConstFill(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSdmaConstFill");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaCopyLinear(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSdmaCopyLinear");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaCopyTiled(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSdmaCopyTiled");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaCopyWindow(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSdmaCopyWindow");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaFlush(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSdmaFlush");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaGetMinCmdSize(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSdmaGetMinCmdSize");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSdmaOpen(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSdmaOpen");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetCsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetCsShader");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetCsShaderWithModifier(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetCsShaderWithModifier");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetEmbeddedPsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetEmbeddedPsShader");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetEmbeddedVsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetEmbeddedVsShader");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetEsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetEsShader");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetGsRingSizes(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetGsRingSizes");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetGsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetGsShader");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetHsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetHsShader");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetLsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetLsShader");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetPsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetPsShader");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetPsShader350(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetPsShader350");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetResourceRegistrationUserMemory(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetResourceRegistrationUserMemory");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetResourceUserData(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetResourceUserData");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetSpiEnableSqCounters(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetSpiEnableSqCounters");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetSpiEnableSqCountersForUnitInstance(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetSpiEnableSqCountersForUnitInstance");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetupMipStatsReport(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetupMipStatsReport");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetVgtControl(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetVgtControl");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetVsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetVsShader");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetWaveLimitMultiplier(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetWaveLimitMultiplier");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSetWaveLimitMultipliers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSetWaveLimitMultipliers");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmEndSpm(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSpmEndSpm");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmInit(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSpmInit");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmInit2(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSpmInit2");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmSetDelay(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSpmSetDelay");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmSetMuxRam(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSpmSetMuxRam");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmSetMuxRam2(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSpmSetMuxRam2");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmSetSelectCounter(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSpmSetSelectCounter");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmSetSpmSelects(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSpmSetSpmSelects");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmSetSpmSelects2(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSpmSetSpmSelects2");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSpmStartSpm(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSpmStartSpm");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttFini(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttFini");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttFinishTrace(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttFinishTrace");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetBcInfo(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttGetBcInfo");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetGpuClocks(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttGetGpuClocks");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetHiWater(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttGetHiWater");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetStatus(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttGetStatus");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetTraceCounter(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttGetTraceCounter");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetTraceWptr(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttGetTraceWptr");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetWrapCounts(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttGetWrapCounts");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetWrapCounts2(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttGetWrapCounts2");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttGetWritebackLabels(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttGetWritebackLabels");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttInit(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttInit");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSelectMode(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttSelectMode");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSelectTarget(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttSelectTarget");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSelectTokens(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttSelectTokens");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSetCuPerfMask(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttSetCuPerfMask");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSetDceEventWrite(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttSetDceEventWrite");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSetHiWater(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttSetHiWater");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSetTraceBuffer2(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttSetTraceBuffer2");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSetTraceBuffers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttSetTraceBuffers");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSetUserData(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttSetUserData");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSetUserdataTimer(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttSetUserdataTimer");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttStartTrace(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttStartTrace");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttStopTrace(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttStopTrace");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSwitchTraceBuffer(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttSwitchTraceBuffer");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttSwitchTraceBuffer2(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttSwitchTraceBuffer2");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSqttWaitForEvent(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSqttWaitForEvent");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSubmitAndFlipCommandBuffers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSubmitAndFlipCommandBuffers");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSubmitAndFlipCommandBuffersForWorkload(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSubmitAndFlipCommandBuffersForWorkload");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSubmitCommandBuffers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSubmitCommandBuffers");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSubmitCommandBuffersForWorkload(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSubmitCommandBuffersForWorkload");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmSubmitDone(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmSubmitDone");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUnmapComputeQueue(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmUnmapComputeQueue");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUnregisterAllResourcesForOwner(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmUnregisterAllResourcesForOwner");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUnregisterOwnerAndResources(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmUnregisterOwnerAndResources");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUnregisterResource(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmUnregisterResource");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUpdateGsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmUpdateGsShader");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUpdateHsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmUpdateHsShader");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUpdatePsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmUpdatePsShader");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUpdatePsShader350(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmUpdatePsShader350");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmUpdateVsShader(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmUpdateVsShader");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateCommandBuffers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmValidateCommandBuffers");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateDisableDiagnostics(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmValidateDisableDiagnostics");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateDisableDiagnostics2(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmValidateDisableDiagnostics2");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateDispatchCommandBuffers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmValidateDispatchCommandBuffers");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateDrawCommandBuffers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmValidateDrawCommandBuffers");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateGetDiagnosticInfo(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmValidateGetDiagnosticInfo");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateGetDiagnostics(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmValidateGetDiagnostics");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateGetVersion(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmValidateGetVersion");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateOnSubmitEnabled(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmValidateOnSubmitEnabled");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidateResetState(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmValidateResetState");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmValidationRegisterMemoryCheckCallback(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmValidationRegisterMemoryCheckCallback");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceRazorCaptureCommandBuffersOnlyImmediate(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceRazorCaptureCommandBuffersOnlyImmediate");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceRazorCaptureCommandBuffersOnlySinceLastFlip(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceRazorCaptureCommandBuffersOnlySinceLastFlip");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceRazorCaptureImmediate(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceRazorCaptureImmediate");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceRazorCaptureSinceLastFlip(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceRazorCaptureSinceLastFlip");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceRazorIsLoaded(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceRazorIsLoaded");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_Bj0GWi1jWcM(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_Bj0GWi1jWcM");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_DKusr7JYQp0(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_DKusr7JYQp0");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_FQzzNvwumaM(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_FQzzNvwumaM");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_F8pof57lLUk(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_F8pof57lLUk");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_GHC4n3Wca0U(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_GHC4n3Wca0U");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_JvkCnvaKlV4(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_JvkCnvaKlV4");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_MB49u6sJLbA(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_MB49u6sJLbA");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_MLr+Fyrxf+8(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_MLr+Fyrxf+8");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_Pmo+ggPZUxc(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_Pmo+ggPZUxc");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_QP7vDGU0xDQ(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_QP7vDGU0xDQ");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_QWuQed5Mus4(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_QWuQed5Mus4");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_R3TYO7Tdv5o(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_R3TYO7Tdv5o");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_UGePHM7rmgA(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_UGePHM7rmgA");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_VKLsX6TGJBM(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_VKLsX6TGJBM");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_WpxSyDE4rms(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_WpxSyDE4rms");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_XSIZOjHqEUI(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_XSIZOjHqEUI");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_clo23rtglI0(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_clo23rtglI0");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_gCGlAvphubs(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_gCGlAvphubs");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_nQAv4PpA8OY(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_nQAv4PpA8OY");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_nSl-NqcCi3E(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_nSl-NqcCi3E");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_otfsenvPebM(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_otfsenvPebM");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_qhKjy4mQhUo(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_qhKjy4mQhUo");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_rcjdwAUCC8Y(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_rcjdwAUCC8Y");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_sKhoi2ectC0(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_sKhoi2ectC0");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_tIkCC1FXpf8(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_tIkCC1FXpf8");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_ut57TBmRQN0(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_ut57TBmRQN0");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_0VEbnc-7Pdk(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_0VEbnc-7Pdk");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_1TRGZJsC5Y4(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_1TRGZJsC5Y4");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_2Lbo4o4e8KM(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_2Lbo4o4e8KM");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_2T1zOhnddFQ(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_2T1zOhnddFQ");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_3plUQ7wqgxc(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_3plUQ7wqgxc");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_326VKBUMI-8(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_326VKBUMI-8");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_7LTGukH+M1A(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_7LTGukH+M1A");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebugModuleReset(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDebugModuleReset");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDebugReset(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDebugReset");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_xMMot887QXE(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_xMMot887QXE");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitToDefaultContextStateInternalCommand(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawInitToDefaultContextStateInternalCommand");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmDrawInitToDefaultContextStateInternalSize(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmDrawInitToDefaultContextStateInternalSize");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmFindResources(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmFindResources");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmGetResourceRegistrationBuffers(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmGetResourceRegistrationBuffers");
	return ORBIS_OK;
}

int PS4_SYSV_ABI sceGnmRegisterOwnerForSystem(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: sceGnmRegisterOwnerForSystem");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_HEOIaxbuVTA(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_HEOIaxbuVTA");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_gQNwGezNDgE(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_gQNwGezNDgE");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_v7QcBXR48L8(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_v7QcBXR48L8");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_5R1E24FRI4w(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_5R1E24FRI4w");
	return ORBIS_OK;
}

int PS4_SYSV_ABI Func_+RaJBCVJZVM(void)
{
	LOG_UNIMPLEMENTED("unimplemented function: Func_+RaJBCVJZVM");
	return ORBIS_OK;
}

void RegisterlibSceGnmDriver(Loader::SymbolsResolver * sym) {
 LIB_FUNCTION("b0xyllnVY-I, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmAddEqEvent ),
 LIB_FUNCTION("b08AgtPlHPg, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmAreSubmitsAllowed ),
 LIB_FUNCTION("ihxrbsoSKWc, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmBeginWorkload ),
 LIB_FUNCTION("ffrNQOshows, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmComputeWaitOnAddress ),
 LIB_FUNCTION("EJapNl2+pgU, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmComputeWaitSemaphore ),
 LIB_FUNCTION("5udAm+6boVg, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmCreateWorkloadStream ),
 LIB_FUNCTION("jwCEzr7uEP4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDebuggerGetAddressWatch ),
 LIB_FUNCTION("PNf0G7gvFHQ, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDebuggerHaltWavefront ),
 LIB_FUNCTION("nO-tMnaxJiE, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDebuggerReadGds ),
 LIB_FUNCTION("t0HIQWnvK9E, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDebuggerReadSqIndirectRegister ),
 LIB_FUNCTION("HsLtF4jKe48, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDebuggerResumeWavefront ),
 LIB_FUNCTION("JRKSSV0YzwA, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDebuggerResumeWavefrontCreation ),
 LIB_FUNCTION("jpTMyYB8UBI, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDebuggerSetAddressWatch ),
 LIB_FUNCTION("MJG69Q7ti+s, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDebuggerWriteGds ),
 LIB_FUNCTION("PaFw9w6f808, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDebuggerWriteSqIndirectRegister ),
 LIB_FUNCTION("qpGITzPE+Zc, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDebugHardwareStatus ),
 LIB_FUNCTION("PVT+fuoS9gU, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDeleteEqEvent ),
 LIB_FUNCTION("UtObDRQiGbs, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDestroyWorkloadStream ),
 LIB_FUNCTION("bX5IbRvECXk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDingDong ),
 LIB_FUNCTION("byXlqupd8cE, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDingDongForWorkload ),
 LIB_FUNCTION("HHo1BAljZO8, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDisableMipStatsReport ),
 LIB_FUNCTION("0BzLGljcwBo, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDispatchDirect ),
 LIB_FUNCTION("Z43vKp5k7r0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDispatchIndirect ),
 LIB_FUNCTION("wED4ZXCFJT0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDispatchIndirectOnMec ),
 LIB_FUNCTION("nF6bFRUBRAU, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDispatchInitDefaultHardwareState ),
 LIB_FUNCTION("HlTPoZ-oY7Y, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawIndex ),
 LIB_FUNCTION("GGsn7jMTxw4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawIndexAuto ),
 LIB_FUNCTION("ED9-Fjr8Ta4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawIndexIndirect ),
 LIB_FUNCTION("thbPcG7E7qk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawIndexIndirectCountMulti ),
 LIB_FUNCTION("5q95ravnueg, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawIndexIndirectMulti ),
 LIB_FUNCTION("jHdPvIzlpKc, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawIndexMultiInstanced ),
 LIB_FUNCTION("oYM+YzfCm2Y, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawIndexOffset ),
 LIB_FUNCTION("4v+otIIdjqg, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawIndirect ),
 LIB_FUNCTION("cUCo8OvArrw, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawIndirectCountMulti ),
 LIB_FUNCTION("f5QQLp9rzGk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawIndirectMulti ),
 LIB_FUNCTION("Idffwf3yh8s, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawInitDefaultHardwareState ),
 LIB_FUNCTION("QhnyReteJ1M, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawInitDefaultHardwareState175 ),
 LIB_FUNCTION("0H2vBYbTLHI, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawInitDefaultHardwareState200 ),
 LIB_FUNCTION("yb2cRhagD1I, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawInitDefaultHardwareState350 ),
 LIB_FUNCTION("8lH54sfjfmU, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawInitToDefaultContextState ),
 LIB_FUNCTION("im2ZuItabu4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawInitToDefaultContextState400 ),
 LIB_FUNCTION("stDSYW2SBVM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawOpaqueAuto ),
 LIB_FUNCTION("TLV4mswiZ4A, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDriverCaptureInProgress ),
 LIB_FUNCTION("ODEeJ1GfDtE, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDriverInternalRetrieveGnmInterface ),
 LIB_FUNCTION("4LSXsEKPTsE, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDriverInternalRetrieveGnmInterfaceForGpuDebugger ),
 LIB_FUNCTION("MpncRjHNYRE, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDriverInternalRetrieveGnmInterfaceForGpuException ),
 LIB_FUNCTION("EwjWGcIOgeM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDriverInternalRetrieveGnmInterfaceForHDRScopes ),
 LIB_FUNCTION("3EXdrVC7WFk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDriverInternalRetrieveGnmInterfaceForReplay ),
 LIB_FUNCTION("P9iKqxAGeck, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDriverInternalRetrieveGnmInterfaceForResourceRegistration ),
 LIB_FUNCTION("t-vIc5cTEzg, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDriverInternalRetrieveGnmInterfaceForValidation ),
 LIB_FUNCTION("BvvO8Up88Zc, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDriverInternalVirtualQuery ),
 LIB_FUNCTION("R6z1xM3pW-w, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDriverTraceInProgress ),
 LIB_FUNCTION("d88anrgNoKY, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmDriverTriggerCapture ),
 LIB_FUNCTION("Fa3x75OOLRA, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmEndWorkload ),
 LIB_FUNCTION("4Mv9OXypBG8, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmFindResourcesPublic ),
 LIB_FUNCTION("iBt3Oe00Kvc, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmFlushGarlic ),
 LIB_FUNCTION("GviyYfFQIkc, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetCoredumpAddress ),
 LIB_FUNCTION("meiO-5ZCVIE, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetCoredumpMode ),
 LIB_FUNCTION("O-7nHKgcNSQ, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetCoredumpProtectionFaultTimestamp ),
 LIB_FUNCTION("bSJFzejYrJI, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetDbgGcHandle ),
 LIB_FUNCTION("pd4C7da6sEg, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetDebugTimestamp ),
 LIB_FUNCTION("UoYY0DWMC0U, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetEqEventType ),
 LIB_FUNCTION("H7-fgvEutM0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetEqTimeStamp ),
 LIB_FUNCTION("oL4hGI1PMpw, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetGpuBlockStatus ),
 LIB_FUNCTION("Fwvh++m9IQI, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetGpuCoreClockFrequency ),
 LIB_FUNCTION("tZCSL5ulnB4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetGpuInfoStatus ),
 LIB_FUNCTION("iFirFzgYsvw, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetLastWaitedAddress ),
 LIB_FUNCTION("KnldROUkWJY, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetNumTcaUnits ),
 LIB_FUNCTION("FFVZcCu3zWU, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetOffChipTessellationBufferSize ),
 LIB_FUNCTION("QJjPjlmPAL0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetOwnerName ),
 LIB_FUNCTION("dewXw5roLs0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetPhysicalCounterFromVirtualized ),
 LIB_FUNCTION("fzJdEihTFV4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetProtectionFaultTimeStamp ),
 LIB_FUNCTION("4PKnYXOhcx4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetResourceBaseAddressAndSizeInBytes ),
 LIB_FUNCTION("O0S96YnD04U, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetResourceName ),
 LIB_FUNCTION("UBv7FkVfzcQ, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetResourceShaderGuid ),
 LIB_FUNCTION("bdqdvIkLPIU, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetResourceType ),
 LIB_FUNCTION("UoBuWAhKk7U, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetResourceUserData ),
 LIB_FUNCTION("nEyFbYUloIM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetShaderProgramBaseAddress ),
 LIB_FUNCTION("k7iGTvDQPLQ, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetShaderStatus ),
 LIB_FUNCTION("ln33zjBrfjk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGetTheTessellationFactorRingBufferBaseAddress ),
 LIB_FUNCTION("QLdG7G-PBZo, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGpuPaDebugEnter ),
 LIB_FUNCTION("tVEdZe3wlbY, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmGpuPaDebugLeave ),
 LIB_FUNCTION("NfvOrNzy6sk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmInsertDingDongMarker ),
 LIB_FUNCTION("7qZVNgEu+SY, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmInsertPopMarker ),
 LIB_FUNCTION("aPIZJTXC+cU, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmInsertPushColorMarker ),
 LIB_FUNCTION("W1Etj-jlW7Y, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmInsertPushMarker ),
 LIB_FUNCTION("aj3L-iaFmyk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmInsertSetColorMarker ),
 LIB_FUNCTION("jiItzS6+22g, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmInsertSetMarker ),
 LIB_FUNCTION("URDgJcXhQOs, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmInsertThreadTraceMarker ),
 LIB_FUNCTION("1qXLHIpROPE, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmInsertWaitFlipDone ),
 LIB_FUNCTION("HRyNHoAjb6E, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmIsCoredumpValid ),
 LIB_FUNCTION("jg33rEKLfVs, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmIsUserPaEnabled ),
 LIB_FUNCTION("26PM5Mzl8zc, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmLogicalCuIndexToPhysicalCuIndex ),
 LIB_FUNCTION("RU74kek-N0c, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmLogicalCuMaskToPhysicalCuMask ),
 LIB_FUNCTION("Kl0Z3LH07QI, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmLogicalTcaUnitToPhysical ),
 LIB_FUNCTION("29oKvKXzEZo, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmMapComputeQueue ),
 LIB_FUNCTION("A+uGq+3KFtQ, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmMapComputeQueueWithPriority ),
 LIB_FUNCTION("+N+wrSYBLIw, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmPaDisableFlipCallbacks ),
 LIB_FUNCTION("8WDA9RiXLaw, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmPaEnableFlipCallbacks ),
 LIB_FUNCTION("tNuT48mApTc, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmPaHeartbeat ),
 LIB_FUNCTION("6IMbpR7nTzA, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmQueryResourceRegistrationUserMemoryRequirements ),
 LIB_FUNCTION("+rJnw2e9O+0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmRaiseUserExceptionEvent ),
 LIB_FUNCTION("9Mv61HaMhfA, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmRegisterGdsResource ),
 LIB_FUNCTION("t7-VbMosbR4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmRegisterGnmLiveCallbackConfig ),
 LIB_FUNCTION("ZFqKFl23aMc, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmRegisterOwner ),
 LIB_FUNCTION("nvEwfYAImTs, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmRegisterResource ),
 LIB_FUNCTION("gObODli-OH8, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmRequestFlipAndSubmitDone ),
 LIB_FUNCTION("6YRHhh5mHCs, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmRequestFlipAndSubmitDoneForWorkload ),
 LIB_FUNCTION("f85orjx7qts, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmRequestMipStatsReportAndReset ),
 LIB_FUNCTION("MYRtYhojKdA, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmResetVgtControl ),
 LIB_FUNCTION("hS0MKPRdNr0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSdmaClose ),
 LIB_FUNCTION("31G6PB2oRYQ, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSdmaConstFill ),
 LIB_FUNCTION("Lg2isla2XeQ, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSdmaCopyLinear ),
 LIB_FUNCTION("-Se2FY+UTsI, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSdmaCopyTiled ),
 LIB_FUNCTION("OlFgKnBsALE, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSdmaCopyWindow ),
 LIB_FUNCTION("LQQN0SwQv8c, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSdmaFlush ),
 LIB_FUNCTION("suUlSjWr7CE, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSdmaGetMinCmdSize ),
 LIB_FUNCTION("5AtqyMgO7fM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSdmaOpen ),
 LIB_FUNCTION("KXltnCwEJHQ, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetCsShader ),
 LIB_FUNCTION("Kx-h-nWQJ8A, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetCsShaderWithModifier ),
 LIB_FUNCTION("X9Omw9dwv5M, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetEmbeddedPsShader ),
 LIB_FUNCTION("+AFvOEXrKJk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetEmbeddedVsShader ),
 LIB_FUNCTION("FUHG8sQ3R58, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetEsShader ),
 LIB_FUNCTION("jtkqXpAOY6w, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetGsRingSizes ),
 LIB_FUNCTION("UJwNuMBcUAk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetGsShader ),
 LIB_FUNCTION("VJNjFtqiF5w, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetHsShader ),
 LIB_FUNCTION("vckdzbQ46SI, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetLsShader ),
 LIB_FUNCTION("bQVd5YzCal0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetPsShader ),
 LIB_FUNCTION("5uFKckiJYRM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetPsShader350 ),
 LIB_FUNCTION("q-qhDxP67Hg, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetResourceRegistrationUserMemory ),
 LIB_FUNCTION("K3BKBBYKUSE, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetResourceUserData ),
 LIB_FUNCTION("0O3xxFaiObw, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetSpiEnableSqCounters ),
 LIB_FUNCTION("lN7Gk-p9u78, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetSpiEnableSqCountersForUnitInstance ),
 LIB_FUNCTION("+xuDhxlWRPg, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetupMipStatsReport ),
 LIB_FUNCTION("cFCp0NX8wf0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetVgtControl ),
 LIB_FUNCTION("gAhCn6UiU4Y, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetVsShader ),
 LIB_FUNCTION("y+iI2lkX+qI, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetWaveLimitMultiplier ),
 LIB_FUNCTION("XiyzNZ9J4nQ, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSetWaveLimitMultipliers ),
 LIB_FUNCTION("kkn+iy-mhyg, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSpmEndSpm ),
 LIB_FUNCTION("aqhuK2Mj4X4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSpmInit ),
 LIB_FUNCTION("KHpZ9hJo1c0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSpmInit2 ),
 LIB_FUNCTION("QEsMC+M3yjE, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSpmSetDelay ),
 LIB_FUNCTION("hljMAxTLNF0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSpmSetMuxRam ),
 LIB_FUNCTION("bioGsp74SLM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSpmSetMuxRam2 ),
 LIB_FUNCTION("cMWWYeqQQlM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSpmSetSelectCounter ),
 LIB_FUNCTION("-zJi8Vb4Du4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSpmSetSpmSelects ),
 LIB_FUNCTION("xTsOqp-1bE4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSpmSetSpmSelects2 ),
 LIB_FUNCTION("AmmYLcJGTl0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSpmStartSpm ),
 LIB_FUNCTION("UHDiSFDxNao, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttFini ),
 LIB_FUNCTION("a3tLC56vwug, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttFinishTrace ),
 LIB_FUNCTION("L-owl1dSKKg, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttGetBcInfo ),
 LIB_FUNCTION("LQtzqghKQm4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttGetGpuClocks ),
 LIB_FUNCTION("wYN5mmv6Ya8, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttGetHiWater ),
 LIB_FUNCTION("9X4SkENMS0M, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttGetStatus ),
 LIB_FUNCTION("lbMccQM2iqc, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttGetTraceCounter ),
 LIB_FUNCTION("DYAC6JUeZvM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttGetTraceWptr ),
 LIB_FUNCTION("pS2tjBxzJr4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttGetWrapCounts ),
 LIB_FUNCTION("rXV8az6X+fM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttGetWrapCounts2 ),
 LIB_FUNCTION("ARS+TNLopyk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttGetWritebackLabels ),
 LIB_FUNCTION("X6yCBYPP7HA, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttInit ),
 LIB_FUNCTION("2IJhUyK8moE, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttSelectMode ),
 LIB_FUNCTION("QA5h6Gh3r60, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttSelectTarget ),
 LIB_FUNCTION("F5XJY1XHa3Y, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttSelectTokens ),
 LIB_FUNCTION("wJtaTpNZfH4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttSetCuPerfMask ),
 LIB_FUNCTION("kY4dsQh+SH4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttSetDceEventWrite ),
 LIB_FUNCTION("7XRH1CIfNpI, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttSetHiWater ),
 LIB_FUNCTION("05YzC2r3hHo, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttSetTraceBuffer2 ),
 LIB_FUNCTION("ASUric-2EnI, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttSetTraceBuffers ),
 LIB_FUNCTION("gPxYzPp2wlo, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttSetUserData ),
 LIB_FUNCTION("d-YcZX7SIQA, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttSetUserdataTimer ),
 LIB_FUNCTION("ru8cb4he6O8, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttStartTrace ),
 LIB_FUNCTION("gVuGo1nBnG8, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttStopTrace ),
 LIB_FUNCTION("OpyolX6RwS0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttSwitchTraceBuffer ),
 LIB_FUNCTION("dl5u5eGBgNk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttSwitchTraceBuffer2 ),
 LIB_FUNCTION("QLzOwOF0t+A, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSqttWaitForEvent ),
 LIB_FUNCTION("xbxNatawohc, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSubmitAndFlipCommandBuffers ),
 LIB_FUNCTION("Ga6r7H6Y0RI, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSubmitAndFlipCommandBuffersForWorkload ),
 LIB_FUNCTION("zwY0YV91TTI, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSubmitCommandBuffers ),
 LIB_FUNCTION("jRcI8VcgTz4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSubmitCommandBuffersForWorkload ),
 LIB_FUNCTION("yvZ73uQUqrk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmSubmitDone ),
 LIB_FUNCTION("ArSg-TGinhk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmUnmapComputeQueue ),
 LIB_FUNCTION("yhFCnaz5daw, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmUnregisterAllResourcesForOwner ),
 LIB_FUNCTION("fhKwCVVj9nk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmUnregisterOwnerAndResources ),
 LIB_FUNCTION("k8EXkhIP+lM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmUnregisterResource ),
 LIB_FUNCTION("nLM2i2+65hA, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmUpdateGsShader ),
 LIB_FUNCTION("GNlx+y7xPdE, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmUpdateHsShader ),
 LIB_FUNCTION("4MgRw-bVNQU, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmUpdatePsShader ),
 LIB_FUNCTION("mLVL7N7BVBg, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmUpdatePsShader350 ),
 LIB_FUNCTION("V31V01UiScY, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmUpdateVsShader ),
 LIB_FUNCTION("iCO804ZgzdA, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmValidateCommandBuffers ),
 LIB_FUNCTION("SXw4dZEkgpA, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmValidateDisableDiagnostics ),
 LIB_FUNCTION("BgM3t3LvcNk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmValidateDisableDiagnostics2 ),
 LIB_FUNCTION("qGP74T5OWJc, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmValidateDispatchCommandBuffers ),
 LIB_FUNCTION("hsZPf1lON7E, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmValidateDrawCommandBuffers ),
 LIB_FUNCTION("RX7XCNSaL6I, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmValidateGetDiagnosticInfo ),
 LIB_FUNCTION("5SHGNwLXBV4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmValidateGetDiagnostics ),
 LIB_FUNCTION("HzMN7ANqYEc, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmValidateGetVersion ),
 LIB_FUNCTION("rTIV11nMQuM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmValidateOnSubmitEnabled ),
 LIB_FUNCTION("MBMa6EFu4Ko, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmValidateResetState ),
 LIB_FUNCTION("Q7t4VEYLafI, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceGnmValidationRegisterMemoryCheckCallback ),
 LIB_FUNCTION("xeTLfxVIQO4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceRazorCaptureCommandBuffersOnlyImmediate ),
 LIB_FUNCTION("9thMn+uB1is, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceRazorCaptureCommandBuffersOnlySinceLastFlip ),
 LIB_FUNCTION("u9YKpRRHe-M, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceRazorCaptureImmediate ),
 LIB_FUNCTION("4UFagYlfuAM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceRazorCaptureSinceLastFlip ),
 LIB_FUNCTION("f33OrruQYbM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , sceRazorIsLoaded ),
 LIB_FUNCTION("Bj0GWi1jWcM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_Bj0GWi1jWcM ),
 LIB_FUNCTION("DKusr7JYQp0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_DKusr7JYQp0 ),
 LIB_FUNCTION("FQzzNvwumaM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_FQzzNvwumaM ),
 LIB_FUNCTION("F8pof57lLUk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_F8pof57lLUk ),
 LIB_FUNCTION("GHC4n3Wca0U, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_GHC4n3Wca0U ),
 LIB_FUNCTION("JvkCnvaKlV4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_JvkCnvaKlV4 ),
 LIB_FUNCTION("MB49u6sJLbA, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_MB49u6sJLbA ),
 LIB_FUNCTION("MLr+Fyrxf+8, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_MLr+Fyrxf+8 ),
 LIB_FUNCTION("Pmo+ggPZUxc, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_Pmo+ggPZUxc ),
 LIB_FUNCTION("QP7vDGU0xDQ, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_QP7vDGU0xDQ ),
 LIB_FUNCTION("QWuQed5Mus4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_QWuQed5Mus4 ),
 LIB_FUNCTION("R3TYO7Tdv5o, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_R3TYO7Tdv5o ),
 LIB_FUNCTION("UGePHM7rmgA, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_UGePHM7rmgA ),
 LIB_FUNCTION("VKLsX6TGJBM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_VKLsX6TGJBM ),
 LIB_FUNCTION("WpxSyDE4rms, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_WpxSyDE4rms ),
 LIB_FUNCTION("XSIZOjHqEUI, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_XSIZOjHqEUI ),
 LIB_FUNCTION("clo23rtglI0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_clo23rtglI0 ),
 LIB_FUNCTION("gCGlAvphubs, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_gCGlAvphubs ),
 LIB_FUNCTION("nQAv4PpA8OY, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_nQAv4PpA8OY ),
 LIB_FUNCTION("nSl-NqcCi3E, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_nSl-NqcCi3E ),
 LIB_FUNCTION("otfsenvPebM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_otfsenvPebM ),
 LIB_FUNCTION("qhKjy4mQhUo, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_qhKjy4mQhUo ),
 LIB_FUNCTION("rcjdwAUCC8Y, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_rcjdwAUCC8Y ),
 LIB_FUNCTION("sKhoi2ectC0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_sKhoi2ectC0 ),
 LIB_FUNCTION("tIkCC1FXpf8, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_tIkCC1FXpf8 ),
 LIB_FUNCTION("ut57TBmRQN0, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_ut57TBmRQN0 ),
 LIB_FUNCTION("0VEbnc-7Pdk, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_0VEbnc-7Pdk ),
 LIB_FUNCTION("1TRGZJsC5Y4, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_1TRGZJsC5Y4 ),
 LIB_FUNCTION("2Lbo4o4e8KM, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_2Lbo4o4e8KM ),
 LIB_FUNCTION("2T1zOhnddFQ, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_2T1zOhnddFQ ),
 LIB_FUNCTION("3plUQ7wqgxc, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_3plUQ7wqgxc ),
 LIB_FUNCTION("326VKBUMI-8, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_326VKBUMI-8 ),
 LIB_FUNCTION("7LTGukH+M1A, libSceGnmDriver , 1 , libSceGnmDriver, 1, 1 , Func_7LTGukH+M1A ),
 LIB_FUNCTION("dqPBvjFVpTA, libSceGnmDebugModuleReset , 1 , libSceGnmDriver, 1, 1 , sceGnmDebugModuleReset ),
 LIB_FUNCTION("RNPAItiMLIg, libSceGnmDebugReset , 1 , libSceGnmDriver, 1, 1 , sceGnmDebugReset ),
 LIB_FUNCTION("xMMot887QXE, libSceGnmDebugReset , 1 , libSceGnmDriver, 1, 1 , Func_xMMot887QXE ),
 LIB_FUNCTION("pF1HQjbmQJ0, libSceGnmDriverCompat , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawInitToDefaultContextStateInternalCommand ),
 LIB_FUNCTION("jajhf-Gi3AI, libSceGnmDriverCompat , 1 , libSceGnmDriver, 1, 1 , sceGnmDrawInitToDefaultContextStateInternalSize ),
 LIB_FUNCTION("vbcR4Ken6AA, libSceGnmDriverResourceRegistration , 1 , libSceGnmDriver, 1, 1 , sceGnmFindResources ),
 LIB_FUNCTION("eLQbNsKeTkU, libSceGnmDriverResourceRegistration , 1 , libSceGnmDriver, 1, 1 , sceGnmGetResourceRegistrationBuffers ),
 LIB_FUNCTION("j6mSQs3UgaY, libSceGnmDriverResourceRegistration , 1 , libSceGnmDriver, 1, 1 , sceGnmRegisterOwnerForSystem ),
 LIB_FUNCTION("HEOIaxbuVTA, libSceGnmDriverResourceRegistration , 1 , libSceGnmDriver, 1, 1 , Func_HEOIaxbuVTA ),
 LIB_FUNCTION("gQNwGezNDgE, libSceGnmDriverResourceRegistration , 1 , libSceGnmDriver, 1, 1 , Func_gQNwGezNDgE ),
 LIB_FUNCTION("v7QcBXR48L8, libSceGnmDriverResourceRegistration , 1 , libSceGnmDriver, 1, 1 , Func_v7QcBXR48L8 ),
 LIB_FUNCTION("5R1E24FRI4w, libSceGnmDriverResourceRegistration , 1 , libSceGnmDriver, 1, 1 , Func_5R1E24FRI4w ),
 LIB_FUNCTION("+RaJBCVJZVM, libSceGnmDriverResourceRegistration , 1 , libSceGnmDriver, 1, 1 , Func_+RaJBCVJZVM ),
 LIB_FUNCTION("Fwvh++m9IQI, libSceGnmGetGpuCoreClockFrequency , 1 , libSceGnmDriver, 1, 1 , sceGnmGetGpuCoreClockFrequency ),
 LIB_FUNCTION("R3TYO7Tdv5o, libSceGnmWaitFreeSubmit , 1 , libSceGnmDriver, 1, 1 , Func_R3TYO7Tdv5o ),
 LIB_FUNCTION("ut57TBmRQN0, libSceGnmWaitFreeSubmit , 1 , libSceGnmDriver, 1, 1 , Func_ut57TBmRQN0 ),
};

}