# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Linux-Qt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch submodules
      run: git submodule update --init --recursive

    - name: Install misc packages
      run: |
       sudo apt-get update && sudo apt install libx11-dev libgl1-mesa-glx mesa-common-dev libfuse2 libwayland-dev

    - name: Install newer Clang
      run: |
       wget https://apt.llvm.org/llvm.sh
       chmod +x ./llvm.sh
       sudo ./llvm.sh 17
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version:      6.6.1
        host:         linux
        target:       desktop
        #arch:         clang++-17
        dir:          ${{ runner.temp }}
        #modules:      qtcharts qt3d
        setup-python: false  
          
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=clang-17 -DCMAKE_CXX_COMPILER=clang++-17

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

#    - name: Run AppImage packaging script
#      run:  |
#        chmod +x .github/linux-appimage-qt.sh
#        ./.github/linux-appimage-qt.sh

#    - name: Upload executable
#      uses: actions/upload-artifact@v2
#      with:
#        name: Linux executable
#        path: './Shadps4-x86_64.AppImage' 